apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ingress
  namespace: ingress-nginx
spec:
  ports:
  - name: http
    nodePort: 30090
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30553
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx" 
spec:
  rules:
  - host: gitlab.krei.co.kr
    http:
      paths:
      - backend:
          serviceName: gitlab
          servicePort: 90  
